language: minimal
services:
- docker
addons:
  apt:
    update: true
before_install:
- sudo apt-get install -y curl openssl ca-certificates
- sudo apt-get install -y make
- sudo apt-get install -y qemu-user-static
env:
  global:
    - PARALLELMFLAGS="-j2"
  matrix:
    - MARCH=amd64   CHECK_TARGET=memcheck
    - MARCH=arm32v7 CHECK_TARGET=check
before_script:
- make MARCH=$MARCH
script:
- make MARCH=$MARCH $CHECK_TARGET
